version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  assignees:
  - franky47
  labels:
  - dependencies
